### ISSUE TITLE
Docker issues

### ISSUE THREAD

**Issue by scallen210** [aveao/splork#1]
Docker doesnt install

**Comment by aveao** [comment]
Hi! Can you detail what you tried a bit more, and post the error that you're getting?

**Comment by scallen210** [comment]
![image](https://user-images.githubusercontent.com/91575226/226146925-c56302d4-62ea-40f1-bc2f-c73146e8b84c.png)

**Comment by scallen210** [comment]
![image](https://user-images.githubusercontent.com/91575226/226146947-4ad86bac-7c7d-484a-89c5-e864dfe1eef7.png)

**Comment by aveao** [comment]
Looks like this: https://github.com/docker/buildx/issues/426#issuecomment-723208580

theoretically not my fault, disable dockerkit, or use wsl/linux.

I accept that this is a bad solution & I am annoyed that there's no good explanations as to how to fix this. will look into it tho.

**Comment by aveao** [comment]
actually looks like you're not on the right directory. run the docker command on the splork folder, not your home folder.

https://github.com/docker/for-win/issues/8781

closing issue, will extend readme.
