### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by DarkVinceX** [aveao/splork#2]
When trying to build splork with my image (funkybeats.png), it says that it cannot find the file or directory.
![2023-05-03 (1)](https://user-images.githubusercontent.com/132524567/236591514-70286979-2e85-4142-86ef-62039853d31f.png)

**Comment by aveao** [comment]
Can you show youe images folder under splork?

**Comment by DarkVinceX** [comment]
Sure thing
![2023-05-06](https://user-images.githubusercontent.com/132524567/236641807-15c7144a-e5bb-45bc-b31c-a66d7d6249b4.png)

**Comment by ivarss** [comment]
Sadly having the same issue on my end, Even if i try to build using the sample image as your code initially is written to it still outright does not even find the directory or file.

**Comment by aveao** [comment]
Looking into it. I didn't have a windows machine around for the longest but I'll try my luck with a VM in a bit.

**Comment by aveao** [comment]
Blehhh. I spent 2 hours fighting windows.

Ramble:
- Docker for Windows requires Hyper-V (WSL2 alsl uses Hyper-V). To use it I needed to get nested virtualization working in VirtualBox, but that lead to boot issues even tho i had it on my system and kernel.
- So; I rented a Windows Server VM from GCP (which amusingly cost $50/mo for the server and $60/mo for the windows license, at least billed per second).
- Nothing went right on that box either. Hyper-V was functioning but docker client kept throwing random errors.

Anyhow a friend, @linuxgemini, ended up helping out and they got to the bottom of it: Docker on Windows handles relative paths differently. Why they never added a compat layer is beyond me.

Anyhow, solution is to use the correct relative paths. I added examples on the README. For the record, use the following commands on windows instead:

**Windows Command Prompt:**

```bash
docker run --rm -it -v %cd%/images:/app/images -v %cd%/build:/app/build splork images/sampleimages/blank.png
```

(this command must be run on the splork folder)

**Windows PowerShell:**

```bash
docker run --rm -it -v ${pwd}/images:/app/images -v ${pwd}/build:/app/build splork images/sampleimages/blank.png
```

**Comment by ivarss** [comment]
Oh my god thats amazing, Thank you for looking into it this quickly! Ill have a check with the updated code you posted now to see if it works.

I was actually about to install Linux in a VM to see if it was a windows related issue because it kinda felt like it. But happy it worked out in the end now! :D
